name: Release Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow when code is pushed to the master branch

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "RELEASE_DATE=$(date +'%Y.%-m.%-d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        run: |
          gh release create ${{ env.RELEASE_DATE }} \
            --title "Release ${{ env.RELEASE_DATE }}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}