name: Release Pipeline

on:
  release:
    types: [created]

jobs:
  release-job:
    runs-on: ubuntu-latest
    # Only run if the release targets the 'master' branch
    if: github.event.release.target_commitish == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Release Tag
        run: |
          echo "Release version (tag): ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Target branch/commit: ${{ github.event.release.target_commitish }}"
