name: Release Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow when code is pushed to the master branch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "RELEASE_DATE=$(date +'%Y.%-m.%-d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_DATE }}  # Use the current date as the tag
          release_name: Release ${{ env.RELEASE_DATE }}  # Use the current date as the release name
          draft: false
          prerelease: false
          generate_release_notes: true  # Automatically generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication